// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
int _NumSourceTriangles;

[numthreads(100,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if ((int)id.x >= _NumSourceTriangles) {
        return;
    }
    int x = id.x;
    int y = id.y;
    
    Result[int2(x, y)] = float4(1.0f, 1.0f, 1.0f, 1.0f);
}
